project:
  type: book

book:
  title: "Foundations of Data Science & Causal ML: A Mathematical Journey"
  author: "Caio Velasco"
  date: today
  chapters:
    - index.qmd
    - chapters/01_ch01.qmd
  sidebar:
    style: docked        # left, fixed sidebar with chapters
    search: true
    collapse-level: 1

number-sections: false

format:
  html:
    theme: cosmo
    code-link: true
    math: true
    toc: true
    toc-location: left  # page TOC in the right margin
    grid:
      sidebar-width: 280px
      body-width: 900px
      margin-width: 0px

output-dir: _book
