project:
  type: book
  output-dir: ../_site/pt

book:
  title: "Fundamentos de Ciência de Dados & Causal ML: Uma Jornada Matemática"
  author: "Caio Velasco"
  date: today
  chapters:
    - index.qmd
    - capitulos/01_cap01.qmd
  sidebar:
    style: docked
    search: true
    collapse-level: 1

number-sections: false

format:
  html:
    theme: cosmo
    code-link: true
    math: true
    toc: true
    toc-location: left
    service-workers: false
    grid:
      sidebar-width: 280px
      body-width: 900px
      margin-width: 0px
